fix Profit Switch error
This commit alongside with changes in libs/poolWorker.js
of z-nomp pool fixed this error when trying to switch Profit
Switch manually (node cli.js coinswitch komodo switch0)

clientsToRelinquish.forEach(function (cObj) {
TypeError: Cannot read property 'forEach' of null

Related info:

- https://github.com/UNOMP/unified-node-open-mining-portal/issues/95#issuecomment-204865124 - this solution fixed it with crutches.
- https://github.com/s-nomp/s-nomp/issues/125